#!/bin/bash
# if node is not installed start with
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

# then run this command, if node is already installed you can go straight to this command
npm install -g sass